name: Feature Request
description: Suggest a new feature for Nova Emulator
labels: enhancement
body:
  - type: input
    id: version
    label: App Version
    placeholder: "e.g., 1.1.0"
    attributes:
      required: true

  - type: textarea
    id: description
    label: Feature Description
    placeholder: "Describe the feature you'd like to see."
    attributes:
      required: true

  - type: textarea
    id: problem
    label: Problem Solved
    placeholder: "What problem does this solve? Why do you need this?"

  - type: textarea
    id: solution
    label: Proposed Solution
    placeholder: "How should this feature work?"

  - type: textarea
    id: alternatives
    label: Alternatives Considered
    placeholder: "Any other ways to solve this?"

  - type: checkboxes
    id: checklist
    label: 
    options:
      - label: "I have searched for similar feature requests"
        required: true
      - label: "This is a new feature, not an improvement to existing"
        required: true
